version: '3.2'
services:
  business-card-api:
    # image: codeanish/business-card-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env